services:
  ghost:
    image: pantalk/ghost:mattermost-dev
    pull_policy: build
    build:
      context: ../..
      dockerfile: Dockerfile
      target: ghost
      args:
        PANTALK_VERSION: ${PANTALK_VERSION:-0.0.12}
